#!/usr/bin/env node
/**
 * Writes .env.local with a freshly generated SESSION_SECRET.
 *
 * The secret is generated here, on your machine, and never leaves it. Don't
 * paste it into a chat — not to Claude, not to anyone. Same goes for your
 * Canvas feed URL: anyone holding it can read your whole assignment schedule.
 */
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";

// fileURLToPath, not .pathname — the latter stays percent-encoded, so a folder
// called "hey-brayan v3" resolves to a literal "hey-brayan%20v3" that does not
// exist, and the write fails with ENOENT. Any space in any parent folder.
const OUT = fileURLToPath(new URL("../.env.local", import.meta.url));

if (existsSync(OUT)) {
  console.log(`\n.env.local already exists — not overwriting it.`);
  console.log(`Delete it first if you want to start over.\n`);
  process.exit(0);
}

/**
 * Reads a line without echoing it.
 *
 * `readline` prints every keystroke by default, which leaves the passphrase on
 * screen and in scrollback. Muting the output stream during the answer keeps it
 * off both. Falls back to a normal prompt where the terminal has no TTY.
 */
async function ask(rl, prompt) {
  if (!stdout.isTTY) return rl.question(prompt);
  const answer = rl.question(prompt);
  const write = stdout.write.bind(stdout);
  stdout.write = (chunk, enc, cb) => {
    if (typeof chunk === "string" && chunk.includes("\n")) write(chunk, enc, cb);
    else if (typeof cb === "function") cb();
    return true;
  };
  try {
    return await answer;
  } finally {
    stdout.write = write;
  }
}

const rl = createInterface({ input: stdin, output: stdout });
console.log(`\n  Setting up Daymark.\n  Two questions, then you're running.\n`);

const typed = (await ask(rl, "  Passphrase to open your dashboard: ")).trim();
const generated = !typed;
const passphrase = typed || randomBytes(12).toString("base64url");

// Masked too: this URL is a read-key to the whole assignment schedule, and it
// would otherwise sit in terminal scrollback in plain text.
const ics = (await ask(rl, "  Canvas calendar feed URL (Calendar → Calendar Feed): ")).trim();
await rl.close();

const env = `# Generated by \`npm run setup\`. Never commit this file.

APP_PASSPHRASE="${passphrase}"
SESSION_SECRET="${randomBytes(32).toString("hex")}"

# Local SQLite file — no signup, works immediately.
# Swap for a Turso URL + token when you deploy; Vercel's filesystem is
# ephemeral, so a file: database there would lose your ticks on every deploy.
TURSO_DATABASE_URL="file:local.db"
TURSO_AUTH_TOKEN=""

CANVAS_ICS_URL="${ics}"
CANVAS_BASE_URL="https://canvas.unm.edu"
# Optional. Unlocks real grades and true submission status.
# canvas.unm.edu → Account → Settings → New Access Token.
CANVAS_API_TOKEN=""

LAT="35.1064"
LON="-106.632"
NWS_USER_AGENT="daymark (bquinonez223@gmail.com)"

SPOTIFY_CLIENT_ID=""
SPOTIFY_CLIENT_SECRET=""
SPOTIFY_REFRESH_TOKEN=""
`;

writeFileSync(OUT, env, { mode: 0o600 });

console.log(`\n  Wrote .env.local (readable only by you).`);
// Only printed when we made it up, because otherwise you already know it and
// it has no business sitting in your terminal history.
if (generated) console.log(`  Generated passphrase: ${passphrase}`);
if (ics) {
  // Enough to confirm the paste landed, not enough to be worth stealing.
  const m = ics.match(/user_([^.]+)\.ics\s*$/);
  console.log(
    m ? `  Canvas feed:  …/user_${m[1].slice(0, 4)}…${m[1].slice(-4)}.ics`
      : `  Canvas feed:  set (${ics.length} chars) — expected it to end in .ics`
  );
} else {
  console.log(`  No Canvas URL set — the To do panel will show an error until you add one.`);
}
console.log(`\n  Next:  npm run dev\n`);
